### ISSUE TITLE
Settings screen

### ISSUE THREAD

**Issue by tnam0rken** [PreICO/profittools#2]
Add a settings menu containing:
- [ ] Language
- [ ] Font size
- [ ] Themes
- [ ] Push (Custom notification)
- [ ] Hide visual menu
- [ ] Pin-Code
- [ ] Reset settings
- [ ] Erase private keys

**Comment by r4rdsn** [comment]
Split into several issues and closed in favor of [milestone](https://github.com/fincubator/profittools/milestone/1).
